Operational stack instantiation
VSharp-team/VSharp pull request #117
Opened 2020-12-12 14:57 UTC by kbatoev

2021-01-13 15:31 UTC, MchKosticyn commented on VSharp.SILI.Core/InterpreterBase.fs
> +                    if x.IsResultState newState then x.SetResultState newState
Выглядит, как не очень хорошо спроектированный код, так как ```if x.IsResultState newState then x.SetResultState newState``` вызывается дважды

2021-01-13 15:31 UTC, MchKosticyn commented on VSharp.SILI.Core/Memory.fs
> +        if Option.isNone (List.tryPick (entriesOfFrame >> List.tryPick (fun { key = l; typ = t } -> if l = key then Some t else None)) s.frames) && Option.isNone (MappedStack.tryFind key s.stack) the
Это код из дебага -- он не нужен

2021-01-13 15:31 UTC, MchKosticyn commented on VSharp.SILI/CFA.fs
> +                    | :? bypassDataForEdges as other -> compareData x.minSCCs x.uOut x.vOut other.minSCCs other.uOut other.vOut
Можно написать через сравнение tuple'ов или списков

2021-01-13 15:31 UTC, MchKosticyn commented on VSharp.SILI/CFA.fs
> +            | _ -> __notImplemented__()
Это можно удалить: dead code

2021-01-13 15:34 UTC, kbatoev commented on VSharp.SILI/CFA.fs
> +                    | :? bypassDataForEdges as other -> compareData x.minSCCs x.uOut x.vOut other.minSCCs other.uOut other.vOut
Не знаю, как это сделать с помощью **одного** сопоставления с образцом, чтобы это выглядело красиво.

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI.Core/API.fs
> +
Лишнее

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/CFA.fs
> +                    let states = interpreter.CommonNewObj false (calledMethod :?> ConstructorInfo) cilStateWithoutArgs.state args id // TODO: what if newobj returns a lot of references and states?
Какой ответ на коммент?

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/CFA.fs
> +                | :? MethodInfo as methodInfo when not calledMethod.IsStatic || opCode = System.Reflection.Emit.OpCodes.Callvirt -> // TODO: check if condition `opCode = OpCodes.Callvirt` needed
Какой ответ на коммент?

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/CFA.fs
> +        // TODO: change offset to ip for Vertex
Это планы на будущее?

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/CFA.fs
> +            // TODO: handle cilState'.leaveInstructionExecuted
Это относится к iie?

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/Instruction.fs
> +//    member x.IsFinished = x.isFinished x.ip
Потом оно потребуется?

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/Instruction.fs
> +      isCompleted : bool
Нам нужен этот флажок? Или информации из ip хватит?

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/Instruction.fs
> +//        }
Нужно?

2021-01-13 15:55 UTC, MchKosticyn commented on VSharp.SILI/Interpreter.fs
> +                | FallThrough nextInstruction          -> [Instruction nextInstruction]
Что-то съехало

2021-01-13 16:17 UTC, kbatoev commented on VSharp.SILI/Instruction.fs
> +      isCompleted : bool
На данном этапе нужен. Для iie уберу его.

2021-01-13 16:18 UTC, kbatoev commented on VSharp.SILI/CFA.fs
> +            // TODO: handle cilState'.leaveInstructionExecuted
Нет, убрал.

2021-01-13 16:18 UTC, kbatoev commented on VSharp.SILI/CFA.fs
> +        // TODO: change offset to ip for Vertex
Да

2021-01-13 16:18 UTC, kbatoev commented on VSharp.SILI/Instruction.fs
> +//        }
Убрал.

2021-01-13 16:21 UTC, kbatoev commented on VSharp.SILI/Instruction.fs
> +//    member x.IsFinished = x.isFinished x.ip
Нет, убрал

2021-01-14 08:40 UTC, MchKosticyn commented on VSharp.SILI/Interpreter.fs
> +        let interpret state curV _ _ =
Может совсем убрать последние параметры?
Ведь эта функция вызывается только в одном месте, при том параметры туда передаются всегда одни и те же

2021-01-14 08:40 UTC, MchKosticyn commented on VSharp.SILI/Interpreter.fs
> +    member x.ReduceArrayCreation (arrayType : System.Type) _ (state : state) (parameters : term list) k =
Возможно стоит совсем убрать этот аргумент? Или он нужен будет в будущем?

2021-01-14 10:04 UTC, MchKosticyn commented on VSharp.SILI/Interpreter.fs
> +            interpret state (Instruction 0)) >> List.concat >> k)
Может подставить параметр напрямую в функцию, если он всегда один и тот же?

2021-01-19 18:42 UTC, dvvrd requested changes

2021-01-20 17:23 UTC, dvvrd requested changes

2021-01-20 17:23 UTC, dvvrd commented on VSharp.SILI.Core/API.fs
> +            Merging.guardedApply getAddressTerm refOrPtr
это надо убрать

2021-01-20 17:23 UTC, dvvrd commented on VSharp.SILI.Core/InterpreterBase.fs
> +//                    let state = if isMethodOfStruct then Memory.popStack state else state
закомментированный код

2021-01-20 17:23 UTC, dvvrd commented on VSharp.Test/Tests/Generic.cs
> +        [Ignore("Insufficient information is correct result")]
почему это причина игнорить этот тест? почему не написать в gold-файл результат типа `Insufficient Information, reason: ...`, а в тех тестах, где IIE пробрасывается наружу, не выводить в качестве результата ровно такую строку?

2021-01-20 17:33 UTC, dvvrd approved these changes

2021-01-20 19:25 UTC, merged