DFS searcher with test coverage priority | Stop SILI on coverage achieved
VSharp-team/VSharp pull request #151
Opened 2022-09-01 09:38 UTC by mxprshn

2022-09-01 09:43 UTC, mxprshn commented on VSharp.SILI/LessCoveredByTestsSearcher.fs
> +type internal LessCoveredWithDistanceAsFallbackWeighter(statistics) =
Попробовал сделать еще searcher, который бы брал состояние с наименьшим количеством инструкций, которые не покрыты тестами, а если покрыты все, то брал бы самое ближнее по CFG. Для достижения покрытия 95% на build он не использовался, но в целом тоже работает. Хотя, можно его и выпилить

2022-09-02 04:35 UTC, dvvrd requested changes

2022-09-02 04:35 UTC, dvvrd commented on VSharp.Utils/TestResultsChecker.fs
> +            if coverage >= expectedCoverage then true
Лучше оставить как было, чтобы не упускать любое изменение в поведении движка -- не только регресс, но и прогресс...

2022-09-02 04:35 UTC, dvvrd commented on VSharp.SILI/WeightCombinators.fs
> +namespace VSharp.Interpreter.IL
Предлагаю этот файл помержить с [CombinedWeighter.fs](https://github.com/VSharp-team/VSharp/pull/151/files#diff-5e69db20f035a04534bbeedb6b18251f52aea4a63d97af7c8c5d53501f39dc6f)

2022-09-02 04:35 UTC, dvvrd commented on VSharp.SILI/VSharp.SILI.fsproj
> -        <Exec Command='
это изменение прошу откатить назад -- это портит Rider :)

2022-09-02 04:35 UTC, dvvrd commented on VSharp.SILI/VSharp.SILI.fsproj
> -        <Exec Command='
здесь аналогично

2022-09-02 04:35 UTC, dvvrd commented on VSharp.SILI/Statistics.fs
> +    let totalBlocksCount = Dictionary<Method, uint>()
BlockCount предлагаю сделать свойством у Method -- зачем лишние поиски в хэш-таблице?

2022-09-02 04:35 UTC, dvvrd commented on VSharp.SILI/Statistics.fs
> +    let getTotalBlocksCount (method : Method) : uint =
соответственно, это станет геттером Method.BlocksCount

2022-09-02 04:35 UTC, dvvrd commented on VSharp.SILI/SILI.fs
> +    let branchReleaseTimeout = if options.timeout <= 0 then Int64.MaxValue else timeout * 50L / 100L
почему мы отдаём 50% времени на досчитывание веток? это точно неадекватное поведение для больших таймаутов. возможно, нужно обсудить нелинейный вариант вычисления этой величины

2022-09-02 13:47 UTC, dvvrd requested changes

2022-09-02 13:47 UTC, dvvrd commented on VSharp.SILI/Statistics.fs
> +    let visitedBlocksNotCoveredByTests = Dictionary<cilState, Set<codeLocation>>()
вместо дорогого eager style-пересчитывания можно просто лениво обновлять информацию для каждого state-а

2022-09-02 13:47 UTC, dvvrd commented on VSharp.SILI/Statistics.fs
> +    let visitedBlocks = Dictionary<cilState, Set<codeLocation>>()
это надо убрать внутрь cilState

2022-09-14 14:40 UTC, MchKosticyn reviewed
Пушка! Осталась пара синтаксических исправлений

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.IL/CFG.fs
> +    member x.BasicBlocksCount with get() = if x.HasBody then x.CFG.SortedOffsets |> Seq.length |> uint else 0u
Длинные строки кода, которые включают в себя if, рекомендую, как минимум, переносить на следующую строчку, как максимум, переносить и then тоже

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.IL/CFG.fs
> +        blockStart.method.HasBody && blockStart.method.CFG.HasSiblings blockStart.offset
blockStart.method можно вынести в отдельную переменную (иначе получается двойной доступ к полю)

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/CombinedWeighter.fs
> +            Some(uint (max 0 (int bound - int anotherWeight)))
Было бы неплохо выделить тут переменные, которые добавляли бы понимания

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/InterleavedSearcher.fs
> +    let update (parent, newStates) = for searcher, _ in searchersWithStepCount do searcher.Update(parent, newStates)
Вновь длинная строчка, которую лучше перенести

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/InterleavedSearcher.fs
> +    let states() = searchersWithStepCount |> List.unzip |> fst |> Seq.collect (fun s -> s.States()) |> Seq.distinct
Лучше добавить перенос и выделить промежуточные переменные

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/InterleavedSearcher.fs
> +    let states() = searchersWithStepCount |> List.unzip |> fst |> Seq.collect (fun s -> s.States()) |> Seq.distinct
Лучше сделать это без unzip (в collect принимать пару)

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/SILI.fs
> +        | InterleavedMode(base1, stepCount1, base2, stepCount2) -> InterleavedSearcher([mkForwardSearcher base1, stepCount1; mkForwardSearcher base2, stepCount2])
Лучше добавить перенос

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/Statistics.fs
> +    let mutable isVisitedBlocksNotCoveredByTestsRelevant = true
Есть ли возможность минимизировать название без потери информации?

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/Statistics.fs
> +                if currentLoc.method.InCoverageZone then coveringStepsInsideZone <- coveringStepsInsideZone + 1u
Лучше currentLoc.method выделить в отдельную переменную

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/Statistics.fs
> +    member x.GetVisitedBasicBlocksNotCoveredByTests (s : cilState) =
Можно переименовать во что-то, вроде NotAlreadyCoveredBlocks

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/Statistics.fs
> +        if not isVisitedBlocksNotCoveredByTestsRelevant then
Можно попробовать минимизировать название

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/Statistics.fs
> +        if not isVisitedBlocksNotCoveredByTestsRelevant then
Аналогично для других длинных названий переменных и функций

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.Test/IntegrationTests.cs
> +                        if (explorer.Statistics.GetApproximateCoverage(Application.getMethod(unitTest.Method)) >= _expectedCoverage)
Можно вынести "Application.getMethod(unitTest.Method)" в отдельную переменную

2022-09-14 14:40 UTC, MchKosticyn commented on VSharp.SILI/SILI.fs
> +            if state.history |> Seq.exists (not << CodeLocation.isBasicBlockCoveredByTest) then
Можно переименовать предикат в "isAlreadyCovered"

2022-09-14 15:57 UTC, dvvrd approved these changes

2022-09-14 16:05 UTC, merged