Tests Renderer improvements, fixes for virtual methods and mocks
VSharp-team/VSharp pull request #173
Opened 2022-11-07 23:33 UTC by MchKosticyn

- Fixes for mocks and virtual methods
- Rendering mocks
- Other renderer fixes
- Rendered tests added to CI (Appveyor)
- Added JetBrains.Util test

2022-11-09 20:07 UTC, dvvrd commented on VSharp.TestRenderer/IdentifiersCache.cs
>              throw new ArgumentException("ID generator failed!");
можно инкрементить суффикс, пока идентификатор не станет уникальным. иначе можно огрести тут эксепшн для x и x1

2022-11-09 20:16 UTC, dvvrd commented on VSharp.TestRenderer/RendererTool.cs
> +            var stream = File.OpenRead(assemblyPath);
using!

2022-11-09 20:26 UTC, dvvrd commented on VSharp.Utils/Mocking.fs
> +            override x.Initialize (decode : obj -> obj) repr obj =
надо бы пояснить в комментах, зачем нам EnsureInitialized, Initialize и ForceInitialize

2022-11-10 11:23 UTC, MchKosticyn commented on VSharp.TestExtensions/VSharp.TestExtensions.csproj
> +<!--        <Compile Remove="Allocator.cs" />-->
Таким образом Максим Аршинов хотел не компилировать 'Allocator.cs' и 'ObjectsComparer.cs'. Думаю, что для нас это не актуально, поэтому удаляю этот код.

2022-11-15 15:13 UTC, dvvrd requested changes

2022-11-15 15:13 UTC, dvvrd commented on VSharp.TestRenderer/TestsRenderer.cs
> +                .ToList();
ToList, соответственно, не нужен

2022-11-15 16:04 UTC, dvvrd approved these changes

2022-11-15 16:05 UTC, merged