Fixes for UTBot demo
VSharp-team/VSharp pull request #213
Opened 2022-12-27 16:26 UTC by MchKosticyn

2022-12-28 15:30 UTC, mxprshn commented on VSharp.CSharpUtils/StringUtils.cs
> +        public static string ValidStringName(string str)
Мб лучше назвать как-то вроде GetValidIdentifier

2022-12-28 15:31 UTC, mxprshn commented on VSharp.SILI/Instrumenter.fs
> +    //                Logger.trace "Placing probes..."
Есть ли смысл комментить trace-логи? По идее, конечным пользователям их все равно не видно

2022-12-28 15:33 UTC, mxprshn approved these changes

2023-01-18 11:33 UTC, dvvrd requested changes

2023-01-18 11:33 UTC, dvvrd commented on VSharp.CSharpUtils/StringUtils.cs
> +                        where char.IsLetterOrDigit(c)
Тут явно что-то не так: идентификатор `_1`, кажется, станет `1`

2023-01-18 16:16 UTC, dvvrd approved these changes

2023-01-18 16:16 UTC, merged