Serialize generic arguments as recursive xml nodes
VSharp-team/VSharp pull request #216
Opened 2022-12-29 13:46 UTC by mxprshn

Use recursive XML nodes to represent generic arguments instead of fully qualified type name (because of some issues with getting types by fully qualified name)

Fixes issue https://github.com/VSharp-team/VSharp/issues/193

**Merge after https://github.com/VSharp-team/VSharp/pull/213https://github.com/VSharp-team/VSharp/pull/213**

2022-12-30 12:09 UTC, MchKosticyn commented on VSharp.Utils/MemoryGraph.fs
> +            if t.IsGenericType && not <| t.IsConstructedGenericType then
Можно убрать "<|"

2022-12-30 12:09 UTC, MchKosticyn commented on VSharp.Utils/MemoryGraph.fs
> +                Debug.Assert(typ.GetGenericArguments().Length = t.genericArgs.Length)
Можно это условие добавить в предыдущий Assert

2022-12-30 12:09 UTC, MchKosticyn commented on VSharp.Utils/Reflection.fs
>                  AssemblyManager.Resolve moduleName
Тут что-то со сдвигами не так

2022-12-30 12:09 UTC, MchKosticyn commented on VSharp.Utils/Reflection.fs
> +                // NB: this method discards current assembly manager!
А что означает "NB"?

2022-12-30 12:09 UTC, MchKosticyn commented on VSharp.Utils/MemoryGraph.fs
> +                internalfail "Encoding not constructed generic types not supported"
Чтобы дважды не проверять на IsGenericType, можно перенести это внутрь условия на строчке 96

2022-12-30 12:22 UTC, mxprshn commented on VSharp.Utils/Reflection.fs
> +                // NB: this method discards current assembly manager!
nota bene --- "обратите внимание" 😅

2023-01-18 12:07 UTC, dvvrd requested changes

2023-01-18 12:07 UTC, dvvrd commented on VSharp.Utils/Reflection.fs
> +                    // NB: this method discards current assembly manager!
Давай переделаем интерфейс AssemblyManager: уберем все сайд-эффекты из Resolve и Load. Соответственно, весь код, связанный со сборками в Reflection, должен просто *читать* уже загруженные сборки в AssemblyManager, а не форсировать загрузку новых

2023-01-18 12:07 UTC, dvvrd commented on VSharp.Utils/Reflection.fs
> +            match AppDomain.CurrentDomain.GetAssemblies() |> Array.tryFindBack isTargetAssembly with
это не правильно: искать надо  в контексте

2023-01-25 18:00 UTC, mxprshn commented on VSharp.Utils/Reflection.fs
> +            match AppDomain.CurrentDomain.GetAssemblies() |> Array.tryFindBack isTargetAssembly with
Вынес эту логику в AssemblyManager

2023-01-25 18:01 UTC, mxprshn commented on VSharp.Utils/Reflection.fs
> +                    // NB: this method discards current assembly manager!
Переименовал Resolve и Load в Init и LoadAndInit, в AssemblyManager добавил функцию GetResolvedAssembly

2023-01-25 18:09 UTC, mxprshn commented on VSharp.Utils/AssemblyManager.fs
> -        currentResolver <- new AssemblyResolveContext(assembly)
Тут, видимо, была бага: если currentResolver.Assembly = assembly, то все равно currentResolver выкидывается (при этом без dispose)

2023-01-25 19:06 UTC, mxprshn commented on VSharp.Utils/Reflection.fs
> +            match AppDomain.CurrentDomain.GetAssemblies() |> Array.tryFindBack isTargetAssembly with
... и перестал работать резолвинг сборок в Test Runner-е

2023-02-14 09:28 UTC, MchKosticyn approved these changes

2023-02-14 09:31 UTC, merged